.globl _start
_start:
        li a0, 1
        addi a0, a0, 1
        nop
        nop
        nop
        nop
        addi a0, a0, 1
        addi a0, a0, 1
        nop
        nop
        nop
        nop
        addi a0, a0, 1
        nop
        addi a0, a0, 1
        nop
        nop
        nop
        nop
        addi a0, a0, 1
        nop
        nop
        addi a0, a0, 1
        nop
        nop
        nop
        nop
        addi a0, a0, 1
        nop
        nop
        nop
        addi a0, a0, 1
        nop
        nop
        nop
        nop
halt:
        j halt
