#!/bin/sh

verilator \
        --cc rtl/*.v \
        --top-module top \
        --exe main.cpp \
        --trace \
        --report-unoptflat \
        --timing

cd obj_dir
make -f Vtop.mk -j$(nproc)
./Vtop
cd ..

