#!/bin/sh

verilator \
        --cc rtl/*.v \
        --top-module top \
        --exe main.cpp \
        --trace \
        --report-unoptflat \
        --timing

STATUS=$?

if [ ${STATUS} -ne 0 ]; then
        echo -e "Verilator failed with status ${STATUS}. Exiting..."
        exit
fi

cd obj_dir

make -f Vtop.mk -j$(nproc)

./Vtop

cd ..
